cof/cof/urls.py
from django.urls import re_path, include, path
from django.conf.urls import include
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from users import views as user_views
from retina import views as retina_views

urlpatterns = [
    path('', include('retina.urls')),
    # re_path(r'^retina/', include('retina.urls')),
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cof/retina/urls.py
# Copyrights 2020,  Sankara Netralaya & BITS Pilani,
# Contact: sundaresan.raman@pilani.bits-pilani.ac.in

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include
from . import views
from django.contrib import admin
from django.urls import re_path, path


app_name = 'retina'
urlpatterns = [
    # /retina/
    # re_path(r'^$', views.index, name='index'),
    path('', views.index, name='index'),

    # /retina/last/
    re_path(r'^last/$', views.last, name='last'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cof/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register, name='register'),
    # Add other URLs as needed
]

cof/retina/models.py
from django.db import models
from django.core.validators import int_list_validator


class Patient(models.Model):
    patient_id = models.CharField(max_length=15, primary_key=True)
    # patient_name = models.CharField(max_length=50)
    # is_right = models.BooleanField(default=True)
    width = models.IntegerField(default='0')
    height = models.IntegerField(default='0')
    link = models.CharField(max_length=500, default='')
    od_x = models.IntegerField(default='0')
    od_y = models.IntegerField(default='0')
    username = models.CharField(max_length=150,default='')
    is_processed = models.BooleanField(default=False)
    under_process = models.BooleanField(default=False)

    def __str__(self):
        return self.patient_id

cof/users/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

cof/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

cof/retina/views.py
# Copyrights 2020,  Sankara Netralaya & BITS Pilani,
# Contact: sundaresan.raman@pilani.bits-pilani.ac.in

from django.http import HttpResponse
from django.template import loader
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Patient
from os import walk
import pathlib
import os.path
import json
from django.conf import settings
import csv
import re

from datetime import datetime
import os
from openpyxl import Workbook
from PIL import Image

from retina.models import Patient
from retina.resources import PatientResource

static_path = settings.STATIC_PATH


@login_required
def index(request):
    # ASSUMPTION: All files in static folder have an entry in db with filename as the patient_id (primary key)
    all_patients = Patient.objects.all()
    count = all_patients.count()

    # print("Count  = : " + str(all_patients.count()))
    all_over = True
    for i in range(count):
        if all_patients[i].is_processed == False:
            all_over = False
            curr_patient = all_patients[i]
            break
    # print("i = " + str(i))
    if all_over == True:
        return HttpResponse("<h2> All patients are annotated! </h2>")
    else:
        curr_patient = all_patients[i]
        patient_id = curr_patient.patient_id
        up = Patient.objects.get(patient_id=patient_id)
        up.under_process = True
        pid_imgfn = curr_patient.link
        # pid_imgfn = os.path.join(patient_id + ".jpg")
        # Get image dimensions
        # im = Image.open(os.path.join(static_path, pid_imgfn))
        # width, height = im.size
        # print("width = " + str(width))
        # print("height = " + str(height))
        # up.width = width
        # up.height = height

        up.save()

        is_back = "0"
        template = loader.get_template('retina/index.html')
        context = {
            'patient_id': patient_id, 'pid_imgfn': pid_imgfn, 'is_back': is_back
        }
        return HttpResponse(template.render(context, request))


@login_required
def last(request):
    if request.method == 'POST':
        # Last page so no need to check for is_back
        # is_back = 'is_back' in request.POST and request.POST.get('is_back')
        patient_id = 'patient_id' in request.POST and request.POST.get(
            'patient_id')
        patient = Patient.objects.get(patient_id=patient_id)
        # pid_imgfn = os.path.join(patient_id + ".jpg")

        # if is_back == "0":
        my_x = 'my_x' in request.POST and request.POST.get('my_x')
        my_y = 'my_y' in request.POST and request.POST.get('my_y')
        # Save the OD centers
        user = request.user
        patient.username = user.username
        patient.od_x = my_x
        patient.od_y = my_y
        patient.is_processed = True
        patient.under_process = False
        patient.save()
        # Now save this patient onto a csv
        # csv_write(patient_id)
        all_patients = Patient.objects.all()
        count = all_patients.count()
        print("Count in ma = : " + str(all_patients.count()))
        all_over = True
        for i in range(count):
            if all_patients[i].is_processed == False:
                all_over = False
                curr_patient = all_patients[i]
                break
        # print("i = " + str(i))

        if all_over == True:
            patient_resource = PatientResource()
            dataset = patient_resource.export()
            wb = Workbook()
            ws = wb.active
            dateTimeObj = datetime.now()
            timestampStr = dateTimeObj.strftime("%d%b%Y%H%M%S")
            title = "Database" + "_" + str(timestampStr)
            ws.title = "Annotation"
            field_names = patient_resource.get_fields()
            print(field_names)

            for row in dataset:
                ws.append(row)

            fname = title + ".xlsx"
            wb.save(fname)
            return HttpResponse("<h2> All patients are annotated! </h2>")
        else:
            curr_patient = all_patients[i]
            patient_id = curr_patient.patient_id
            pid_imgfn = curr_patient.link

            # Get image dimensions
            pp = Patient.objects.get(patient_id=patient_id)
            # im = Image.open(os.path.join(static_path, pid_imgfn))
            # width, height = im.size
            # print("width = " + str(width))
            # print("height = " + str(height))
            # pp.width = width
            # pp.height = height
            pp.save()
            template = loader.get_template('retina/index.html')
            context = {
                'patient_id': patient_id, 'pid_imgfn': pid_imgfn
            }
            return HttpResponse(template.render(context, request))

cof/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(
                request, f'Your account has been created! You are now able to log in')
            return redirect('cof:login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})


@login_required
def profile(request):
    return render(request, 'users/profile.html')

cof/retina/templates/retina/index.html
<!--
# Copyrights 2020,  Sankara Netralaya & BITS Pilani,
# Contact: sundaresan.raman@pilani.bits-pilani.ac.in
-->

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- loads the path to your staticfiles -->
    {%  load static  %}
    <!--{{pid_imgfn}} -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <link rel="stylesheet" type="text/css" href="{% static 'users/main.css' %}">
    
    {% if title %}
    <title> {{ title }}</title>
    {% else %}
    <title>OPTUS Images Center Identification</title>
    {% endif %}

<style>
        .button {
            background-color: #4CAF50;
            border: none;
            color: white;
            padding: 15px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 25px;
            margin: 4px 2px;
            cursor: pointer;
        }

        .select-style {
            border: 1px solid #ccc;
            border-radius: 3px;
            font-size: 25px;
            color: white;
            padding: 15px 32px;
            text-align: center;
            overflow: hidden;
            background-color: #4CAF50;
        }

        .select-style select {
            padding: 5px 8px;
            width: 250%;
            border: none;
            box-shadow: none;
            background: transparent;
            background-image: none;
        }

        .select-style select:focus {
            outline: none;
        }

    </style>

    <script src = "/static/jquery.min.js">
    </script>
    <script>
    var pid_imgfn = "{{ pid_imgfn }}";
    var patient_id = "{{ patient_id }}";
    // var is_back = "{{ is_back }}"
    </script>

</head>

<body onload="draw();">
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="{% url 'retina:index' %}">Main Page</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav">
                        {% if user.is_authenticated %}
                        <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                        <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                        {% else %}
                        <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                        <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </header>
<h1> Patient ID: <strong> {{ patient_id }} </strong> </h1>    
<!-- <h1> Link: <strong> {{ pid_imgfn }}  </strong> </h1> -->
<h1><p id = "od_text">Please Choose Optic Disk Center by clicking on the image: </p></h1>
    {% if patient_id  %}
        <form id="odform" action="{% url  'retina:last' %}"  method="post"  >
            {% csrf_token %}
            <canvas id="imgCanvas" width="1500" height="1500"  onclick="canvasClick()" style="border:1px solid #000000;"></canvas>
            <!--<img id="pimg" src = "{%  static pid_imgfn  %}" alt = "description" width="1016" height="1016">
            -->
        <div id="hidethis" class = mydiv>
            <!--<label for="my_x" >X: </label>-->
            <!-- <input type="hidden"  id="is_back" name="is_back" value = "0"> -->

                <!--<label for="my_x" >X: </label>-->
            <input type="hidden"  id="my_x" name="my_x" >
                <!-- <label for="my_y" >Y: </label> -->
            <input type="hidden" id="my_y" name="my_y" >

            <!--<label for="my_pidjs" >PidJs</label>-->
            <input type="hidden" id="my_pidjs" name="pid_imgfn"> <br><br>

            <!--<label for="my_patientid" >PatientId</label>-->
            <input type="hidden" id="my_patientid" name="patient_id"> <br><br>
        </div>

            <input type="submit" disabled class = "button" value = "Save" id="submitButton" >
        </form>
    {% else  %}
        <h2> There are no more patients/images!</h2>
    {% endif  %}
    <script>
        console.log(pid_imgfn);
        var canvas = document.getElementById("imgCanvas");
        var context = canvas.getContext("2d");
        var img_buffer = document.createElement('img');
        document.getElementById("my_pidjs").value = pid_imgfn;
        document.getElementById("my_patientid").value = patient_id;
        function draw() {
            img_buffer.onload = function() {
                //img_buffer.width = img_buffer.width/4;
                //img_buffer.height = img_buffer.height/4;
                imgWidth = img_buffer.width/4;
                imgHeight = img_buffer.height/4;
                canvas.width = imgWidth;
                canvas.height = imgHeight;
                context.drawImage(img_buffer, 0, 0, imgWidth, imgHeight);
            };
            
            var img_url = pid_imgfn.replace(/&amp;/g, '&');
            img_buffer.src = img_url;
            console.log(pid_imgfn);
        }
        // Mouse Position
        canvas.addEventListener("click", function (evt) {
            //Enable the save button
            document.getElementById("submitButton").removeAttribute("disabled");
            //Clear the previous rendering by drawCoordAxis() by reloading the imgbuffer
            context.drawImage(img_buffer, 0, 0, canvas.width, canvas.height);
            var mousePos = getMousePos(canvas, evt);
            x = Math.round(mousePos.x).toString();
            y = Math.round(mousePos.y).toString();
            document.getElementById("my_x").value = Math.round(mousePos.x).toString();
            document.getElementById("my_y").value = Math.round(mousePos.y).toString();
            document.getElementById("my_pidjs").value = pid_imgfn;
            document.getElementById("my_patientid").value = patient_id;
            drawCoordAxis(x,y);

        }, false);

        //Get Mouse Position
        function getMousePos(canvas, evt) {
            var rect = canvas.getBoundingClientRect();
            return {
                        x: evt.clientX - rect.left,
                        y: evt.clientY - rect.top
                    };
        }
        function drawCoordAxis(x,y){
            var pointSize = 3; // Change according to the size of the point.
            var ctx = context;
            ctx.fillStyle = "#ff2626"; // Red color
            ctx.beginPath(); //Start path
            // Draw a point using the arc function of the canvas with a point structure.
            ctx.arc(x, y, pointSize, 0, Math.PI * 2, true);
            ctx.fill(); // Close the path and fill.
            // Now draw major and minor axes
            ctx.strokeStyle = "#2626ff"; // Red color
            ctx.beginPath();
            ctx.moveTo(x,0);
            ctx.lineTo(x, canvas.height);
            ctx.stroke();
            ctx.beginPath();
            ctx.moveTo(0,y);
            ctx.lineTo(canvas.width,y);
            ctx.stroke();
        }

        function canvasClick(){
        }

    </script>

    <script>
        //$(document).ready(function(){
        //    $("#hideme").hide();
        // });
    </script>
</body>
</html>

cof/retina/templates/retina/temp.html
from datetime import datetime
import os
from openpyxl import Workbook
from PIL import Image

from retina.models import Patient
from retina.resources import PatientResource
patient_resource = PatientResource()
dataset = patient_resource.export()
wb = Workbook()
ws = wb.active
dateTimeObj = datetime.now()
timestampStr = dateTimeObj.strftime("%d%b%Y%H%M%S")
title = "Database" + "_" + str(timestampStr)
ws.title = "Annotation"
field_names=patient_resource.get_fields()
print(field_names)

for row in dataset:
    ws.append(row)

fname = title + ".xlsx"
wb.save(fname)

cof/users/templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'users/main.css' %}">

    {% if title %}
    <title> {{ title }}</title>
    {% else %}
    <title>OPTUS Images Center Identification</title>
    {% endif %}
</head>

<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="{% url 'retina:index' %}">Main Page</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav">
                        {% if user.is_authenticated %}
                        <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                        <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                        {% else %}
                        <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                        <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
                {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
                {% endfor %}
                {% endif %}
                {% block content %}{% endblock %}
            </div>
        </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>

</html>

cof/users/templates/users/login.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Log In</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Login</button>
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{% url 'register' %}">Sign Up Now</a>
        </small>
    </div>
</div>
{% endblock content %}

cof/users/templates/users/logout.html
{% extends "users/base.html" %}
{% block content %}
<h2>You have been logged out</h2>
<div class="border-top pt-3">
    <small class="text-muted">
        <a href="{% url 'login' %}">Log In Again</a>
    </small>
</div>
{% endblock content %}

cof/users/templates/users/profile.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <div class="media">
        <div class="media-body">
            <h2 class="account-heading">{{ user.username }}</h2>
            <p class="text-secondary">{{ user.email }}</p>
        </div>
    </div>
    <!-- FORM HERE -->
</div>
{% endblock content %}

cof/users/templates/users/register.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Join Today</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Sign Up</button>
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{% url 'login' %}">Sign In</a>
        </small>
    </div>
</div>
{% endblock content %}